### ISSUE TITLE
does not work for kubernetes jenkins plugin

### ISSUE THREAD

**Issue by robertchen** [cloudbees/java-build-tools-dockerfile#44]
Error is:  Killing container with id docker://jnlp:Need to kill Pod

`def label = "docker-${UUID.randomUUID().toString()}"

podTemplate(label: label, yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: myjnlp
    image: cloudbees/java-build-tools
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
  ) {

  node(label) {
    stage('Build Docker image') {
      git 'https://github.com/jenkinsci/docker-jnlp-slave.git'
      container('myjnlp') {
        sh "ant -version"
      }
    }
  }
}`

**Comment by cyrille-leclerc** [comment]
Problem reproduced. Log messages:

```
Aug 07, 2019 8:19:22 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Template for label docker-621262bb-290f-440c-ab01-dd842be324bf: Kubernetes Pod Template
Aug 07, 2019 8:19:22 AM INFO com.cloudbees.jenkins.plugins.kube.KubernetesNodeProvisionerStrategy apply
[docker-621262bb-290f-440c-ab01-dd842be324bf] Planned 1 new nodes
Aug 07, 2019 8:19:24 AM INFO hudson.slaves.NodeProvisioner$2 run
Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Aug 07, 2019 8:19:24 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Created Pod: core/docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7
Aug 07, 2019 8:19:24 AM INFO okhttp3.internal.platform.Platform log
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Aug 07, 2019 8:19:26 AM WARNING hudson.TcpSlaveAgentListener$ConnectionHandler run
Connection #21 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:254)

Aug 07, 2019 8:19:26 AM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted JNLP4-connect connection #22 from ip-192-168-133-196.ec2.internal/192.168.133.196:47662
Aug 07, 2019 8:20:11 AM INFO org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution$PodTemplateCallback finished
Removing pod template docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h from cloud kubernetes
Aug 07, 2019 8:20:11 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
front-team/test-java-build-tools #1 completed: ABORTED
Aug 07, 2019 8:20:21 AM INFO com.cloudbees.opscenter.context.config.CloudConfigurationSnippetHandler consume
Applied/updated Clouds configuration
Aug 07, 2019 8:20:34 AM WARNING com.cloudbees.jenkins.plugins.kube.common.BackOffCounter recordError
Will try again in 8 seconds.
Aug 07, 2019 8:20:34 AM WARNING org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Error in provisioning; agent=KubernetesSlave name: docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7, template=PodTemplate{inheritFrom='', name='docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h', namespace='', label='docker-621262bb-290f-440c-ab01-dd842be324bf', nodeSelector='', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[org.csanchez.jenkins.plugins.kubernetes.volumes.ConfigMapVolume@50ea30b1], containers=[ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:alpine', workingDir='/home/jenkins', command='/bin/sh', args='/var/jenkins_config/jenkins-agent', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceLimitCpu='', resourceLimitMemory='', livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@37ee283c}], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821], yamls=[
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: myjnlp
    image: cloudbees/java-build-tools
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
]}
java.lang.IllegalStateException: Pod has terminated containers: core/docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7 (myjnlp)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:167)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:188)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:131)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:128)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Aug 07, 2019 8:20:34 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for agent docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7
Aug 07, 2019 8:20:34 AM WARNING jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
Computer.threadPoolForRemoting [#13973] for docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7 terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
	at hudson.remoting.Channel.close(Channel.java:1452)
	at hudson.remoting.Channel.close(Channel.java:1405)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:844)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:105)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:753)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Aug 07, 2019 8:20:34 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
Terminated Kubernetes instance for agent core/docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7
Aug 07, 2019 8:20:34 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Disconnected computer docker-621262bb-290f-440c-ab01-dd842be324bf-wb45h-jhvx7
```

**Comment by lucasmellos** [comment]
Same issue here!

**Comment by ThetaSinner** [comment]
I can't share my configuration because my organisation won't let me. However, we have this working on Jenkins with the Kubernetes plugin.
Have you tried configuring an agent definition under Manage Jenkins -> Kubernetes plugin config? This worked much better for me.
Also, the next image from this one (I think?) provides JNLP which is very helpful, definitely worth a try -> cloudbees/jnlp-slave-with-java-build-tools
Just make sure you call the container 'jnlp', otherwise it will try to launch a second container to provide JNLP for you.
